# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: ADO-VMSS
  vmImage: ubuntu-latest

jobs:
  - job: Deploy
    steps:
      - task: AzureResourceManagerTemplateDeployment@3
        displayName: 'Validate deployment'
        inputs:
          deploymentScope: 'Subscription'
          azureResourceManagerConnection: 'SC_Azure-ADO'
          subscriptionId: $(subscriptionId)
          location: 'UK West'
          templateLocation: 'Linked artifact'
          csmFile: 'azure_infrastructure\main.bicep'
          csmParametersFile: 'azure_infrastructure\main.parameters.json'
          deploymentMode: 'Validation'